[package]
name = "rustapi"
version = "0.1.0"
edition = "2021"
description = "A FastAPI-style Python web framework with a Rust (tokio/hyper) core"
license = "MIT"
repository = "https://github.com/rajboopathiking/rustapi"

[lib]
name = "rustapi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py38"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
urlencoding = "2.1"
notify = "6.1.1"
signal-hook = "0.4.4"
walkdir = "2.5.0"
indexmap = "2.2.6"
socket2 = "0.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true